# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap_mangen = "0.2.15"
clap_complete = "4.4.4"
clap = "4.4.10"

[dependencies.ncspot]
default-features = false
path = ".."
