# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap_mangen = "0.2.16"
clap_complete = "4.4.6"
clap = "4.4.13"

[dependencies.ncspot]
default-features = false
path = ".."

[lints]
workspace = true
